name: Oxyverse Native Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

            - name: Extract Project ZIP
        run: |
          # Perintah untuk unzip semua file .zip yang ada di repo
          unzip -o *.zip
          
          # PROTOKOL PENTING:
          # Biasanya setelah unzip, file masuk ke dalam folder lagi.
          # Perintah ini mindahin isinya ke luar biar sejajar sama gradlew.
          mv */* . || true
 

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build APK Release
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oxyverse-APK-Result
          path: app/build/outputs/apk/release/*.apk
