name: Flutter APK Builder From Zip

on:
  workflow_dispatch: # Memungkinkan kamu klik tombol "Run workflow" manual dari HP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ekstrak Source Code yoshimutsu.zip
        run: |
          echo "Mengekstrak file yoshimutsu.zip..."
          unzip -o yoshimutsu.zip -d .
          echo "Ekstrak selesai!"
          ls -la # Mengintip struktur folder setelah diekstrak

      - name: Setup Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Clean Build Cache
        run: flutter clean

      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
